// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/brandoyts/job-aggr/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// JobScraper is an autogenerated mock type for the JobScraper type
type JobScraper struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, query, location
func (_m *JobScraper) Fetch(ctx context.Context, query string, location string) ([]model.Job, error) {
	ret := _m.Called(ctx, query, location)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []model.Job
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]model.Job, error)); ok {
		return rf(ctx, query, location)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []model.Job); ok {
		r0 = rf(ctx, query, location)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Job)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, query, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJobScraper creates a new instance of JobScraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobScraper(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobScraper {
	mock := &JobScraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
